config/routes.rb
Rails.application.routes.draw do
  resources :acessos_apis
  resources :tokens
  resources :cars
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/cidades', to: 'estados#lista_cidades'
  get '/bairros', to: 'estados#lista_bairros'
  get '/estados', to: 'estados#index'
  get '/estados-proxy', to: 'estados#proxy'
  get '/token-acesso', to: 'tokens#token_acesso'
  get '/cars-proxy', to: 'cars#proxy'
  
  
  root to: 'home#index'
  # root to: 'home'
end

app/models/acessos_api.rb
class AcessosApi < ApplicationRecord
end

app/controllers/acessos_apis_controller.rb
class AcessosApisController < ApplicationController
  before_action :set_acessos_api, only: %i[ show edit update destroy ]

  # GET /acessos_apis or /acessos_apis.json
  def index
    @acessos_apis = AcessosApi.all
  end

  # GET /acessos_apis/1 or /acessos_apis/1.json
  def show
  end

  # GET /acessos_apis/new
  def new
    @acessos_api = AcessosApi.new
  end

  # GET /acessos_apis/1/edit
  def edit
  end

  # POST /acessos_apis or /acessos_apis.json
  def create
    @acessos_api = AcessosApi.new(acessos_api_params)

    respond_to do |format|
      if @acessos_api.save
        format.html { redirect_to acessos_api_url(@acessos_api), notice: "Acessos api was successfully created." }
        format.json { render :show, status: :created, location: @acessos_api }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @acessos_api.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acessos_apis/1 or /acessos_apis/1.json
  def update
    respond_to do |format|
      if @acessos_api.update(acessos_api_params)
        format.html { redirect_to acessos_api_url(@acessos_api), notice: "Acessos api was successfully updated." }
        format.json { render :show, status: :ok, location: @acessos_api }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @acessos_api.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acessos_apis/1 or /acessos_apis/1.json
  def destroy
    @acessos_api.destroy

    respond_to do |format|
      format.html { redirect_to acessos_apis_url, notice: "Acessos api was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acessos_api
      @acessos_api = AcessosApi.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def acessos_api_params
      params.require(:acessos_api).permit(:token, :url)
    end
end

app/helpers/acessos_apis_helper.rb
module AcessosApisHelper
end

app/views/acessos_apis/_form.html.erb
<%= form_with(model: acessos_api) do |form| %>
  <% if acessos_api.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(acessos_api.errors.count, "error") %> prohibited this acessos_api from being saved:</h2>

      <ul>
        <% acessos_api.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :token %>
    <%= form.text_field :token %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/acessos_apis/edit.html.erb
<h1>Editing Acessos Api</h1>

<%= render 'form', acessos_api: @acessos_api %>

<%= link_to 'Show', @acessos_api %> |
<%= link_to 'Back', acessos_apis_path %>

app/views/acessos_apis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Acessos Apis</h1>

<table>
  <thead>
    <tr>
      <th>Token</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @acessos_apis.each do |acessos_api| %>
      <tr>
        <td><%= acessos_api.token %></td>
        <td><%= acessos_api.url %></td>
        <td><%= link_to 'Show', acessos_api %></td>
        <td><%= link_to 'Edit', edit_acessos_api_path(acessos_api) %></td>
        <td><%= link_to 'Destroy', acessos_api, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Acessos Api', new_acessos_api_path %>

app/views/acessos_apis/new.html.erb
<h1>New Acessos Api</h1>

<%= render 'form', acessos_api: @acessos_api %>

<%= link_to 'Back', acessos_apis_path %>

app/views/acessos_apis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Token:</strong>
  <%= @acessos_api.token %>
</p>

<p>
  <strong>Url:</strong>
  <%= @acessos_api.url %>
</p>

<%= link_to 'Edit', edit_acessos_api_path(@acessos_api) %> |
<%= link_to 'Back', acessos_apis_path %>