config/routes.rb
Rails.application.routes.draw do
  resources :acessos_apis
  resources :tokens
  resources :cars
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/cidades', to: 'estados#lista_cidades'
  get '/bairros', to: 'estados#lista_bairros'
  get '/estados', to: 'estados#index'
  get '/estados-proxy', to: 'estados#proxy'
  get '/token-acesso', to: 'tokens#token_acesso'
  get '/cars-proxy', to: 'cars#proxy'
  
  
  root to: 'home#index'
  # root to: 'home'
end

app/models/token.rb
class Token < ApplicationRecord
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_action :set_token, only: %i[ show edit update destroy ]

  # GET /tokens or /tokens.json
  def index
    @tokens = Token.all
  end

  # GET /tokens/1 or /tokens/1.json
  def show
  end

  # GET /tokens/new
  def new
    @token = Token.new
  end

  # GET /tokens/1/edit
  def edit
  end

  def token_acesso
    token = token.create(valor: SecureRandom.uuid, data_inicial: (Time.zone.now - 10.minutes), data_final: (Time.zone.now + 10.minutes))
    render json: {token:token.valor}, status: 201
  end

  # POST /tokens or /tokens.json
  def create
    @token = Token.new(token_params)

    respond_to do |format|
      if @token.save
        format.html { redirect_to token_url(@token), notice: "Token was successfully created." }
        format.json { render :show, status: :created, location: @token }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tokens/1 or /tokens/1.json
  def update
    respond_to do |format|
      if @token.update(token_params)
        format.html { redirect_to token_url(@token), notice: "Token was successfully updated." }
        format.json { render :show, status: :ok, location: @token }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tokens/1 or /tokens/1.json
  def destroy
    @token.destroy

    respond_to do |format|
      format.html { redirect_to tokens_url, notice: "Token was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_token
      @token = Token.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def token_params
      params.require(:token).permit(:valor, :data_inicial, :data_final)
    end
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/tokens/_form.html.erb
<%= form_with(model: token) do |form| %>
  <% if token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(token.errors.count, "error") %> prohibited this token from being saved:</h2>

      <ul>
        <% token.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor %>
  </div>

  <div class="field">
    <%= form.label :data_inicial %>
    <%= form.datetime_select :data_inicial %>
  </div>

  <div class="field">
    <%= form.label :data_final %>
    <%= form.datetime_select :data_final %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tokens/edit.html.erb
<h1>Editing Token</h1>

<%= render 'form', token: @token %>

<%= link_to 'Show', @token %> |
<%= link_to 'Back', tokens_path %>

app/views/tokens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tokens</h1>

<table>
  <thead>
    <tr>
      <th>Valor</th>
      <th>Data inicial</th>
      <th>Data final</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tokens.each do |token| %>
      <tr>
        <td><%= token.valor %></td>
        <td><%= token.data_inicial %></td>
        <td><%= token.data_final %></td>
        <td><%= link_to 'Show', token %></td>
        <td><%= link_to 'Edit', edit_token_path(token) %></td>
        <td><%= link_to 'Destroy', token, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Token', new_token_path %>

app/views/tokens/new.html.erb
<h1>New Token</h1>

<%= render 'form', token: @token %>

<%= link_to 'Back', tokens_path %>

app/views/tokens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Valor:</strong>
  <%= @token.valor %>
</p>

<p>
  <strong>Data inicial:</strong>
  <%= @token.data_inicial %>
</p>

<p>
  <strong>Data final:</strong>
  <%= @token.data_final %>
</p>

<%= link_to 'Edit', edit_token_path(@token) %> |
<%= link_to 'Back', tokens_path %>